include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/di/di.config.dart"
    - "**/*.config.dart"
    - "lib/i18n/**"
    - "lib/generated/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    avoid_types_on_closure_parameters: false
    omit_local_variable_types: false