name: navigation
description: A project demonstrating clean architecture
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.5.0
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.17
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_fonts: ^4.0.3
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  palette_generator: ^0.3.3+2
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.3
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mockito: ^5.4.2
  retrofit_generator: ^7.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

flutter_gen:
  output: lib/generated/
