name: navigation
description: Recruitment task for simpleclub
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^2.3.3 
  freezed_annotation: ^0.12.0
  injectable: ^1.1.2
  get_it: ^5.0.6
  flutter_bloc: ^7.0.0
  google_fonts: ^1.1.2
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1
  flutter_markdown: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.1.2
  build_runner: ^1.11.1
  pedantic: ^1.8.0
  effective_dart: ^1.3.0
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  retrofit_generator: ^1.4.1+3
  bloc_test: ^8.0.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true

  assets:
  - assets/langs/
  - assets/images/