name: navigation
description: A project demonstrating clean architecture
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  easy_localization: ^3.0.0
  freezed_annotation: ^0.14.2
  injectable: ^1.4.1
  get_it: ^7.1.3
  flutter_bloc: ^7.0.1
  google_fonts: ^2.1.0
  retrofit: ^2.0.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_markdown: ^0.6.2
  palette_generator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  build_runner: ^2.0.4
  flutter_gen_runner: ^3.1.1
  pedantic: ^1.11.1
  effective_dart: ^1.3.2
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.0+1
  bloc_test: ^8.0.2
  mockito: ^5.0.10

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
