name: navigation
description: A project demonstrating clean architecture
publish_to: "none"
version: 1.0.0+1

environment:
  flutter: ">=3.27.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^9.3.0+1
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_markdown: ^0.7.6+1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http_parser: ^4.0.2
  json_annotation: ^4.9.0
  palette_generator: ^0.3.3+2
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^4.0.1
  rxdart: ^0.28.0
  shared_preferences: ^2.1.2

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.7.0
  mockito: ^5.4.2
  retrofit_generator: ^9.1.9

dependency_overrides: 
  analyzer: ^7.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

flutter_gen:
  output: lib/generated/
